sudo: required
dist: xenial

services:
- docker

env:
  global:
    - IMAGE_NAME: $TRAVIS_REPO_SLUG
    - IMAGE_VERSION: $TRAVIS_TAG
    - secure: "mw8FwBPmW9QUF6QH79Bj6ytjck4iZcWPYJiTgHR2MjNy4d8d5rhaaUsQ+qed4R9qWUGymABPvsqe+cgwmIrRzTQKPTU1smmIWh32t+BcTj3qq6kxB4YQjJ7C3y1Sawb4CLtNav8uA96s2Os6rTVS1svp/7kKzuoOoxKEiF2nNv6BkGBpXfDIMUkstUjq7lTHFB/LW/TRikmFyIbZLF0UMVfEzARH0Vhhj5qAiRWZ/Ke/FWg9Gs5LSCZ9zckG83w+u2Spb28/iPTmt6WdbQFQZSHSpjwnMNG4XLEjvi3x4dvFa6TPY5MQnrAYXtIDG1PzcIBvES9HGu4PYzt6OS4XznYSItflNtbTGmsdKJZfZwX/xJI4d33KOXluvpxzaMrpjarSzOIrLWJvvK1uNTiT9NwJOvwGnk4OpF1fTQ+ALN95a0g8ADWV7ebtBnKsJJzKbmEfvz7/CDolLbyt6DWby7oRFLD56VC8kTmQ3tS1sNzSCQgVuZvKrP8X4c9HRr3zYkzQEMAlRFq7EMZ3cwINGDPAyghwlMDyjZVbeoy9gRy2PoiFYFFvkV5EpjSu8ShNkMafpt3nSmxD2Tq4tsS+RsnES1qikYOOW2ahNEdSZ8+ZfQYZD6s2DM7pa2dRXBsUk7/mHgFTrGwv1dy5JdWfq+NgVsAtf+g7r1SY8Aes5VQ="
    - secure: "EQRjq6G7FcTuLO1DXZaWcf3+t5ZIzvNsoRKRykgCmt9HMKDlQN+bvJ6i0B7mFUFNL26OUYntl/7y71mvmo9eSYWbFBC6ew2xd9cnrTsOUeAOXdD969R1XVlM0pcM+v7TeuPm0/e7bBmvJ6f8tH7jCcYpsSvTJ8RfS9lKfph0g//tKIn39jdQzMdPGaOFtm3PFHmC1oMtVQiNtRqIliUysQzPDpPl6qj/9qm8RL8iXXvjELXpW3YH1SX7d57S7uU2LWCCTlXD4vczqMNxPr+vR+feoDtoEdLNfvEzvGvrIsehvCmTRiDSj2IM4SdKbu2JBRI9MEviS7GlicnIj1eHdHJ4A9qIIvBLkM+qF5EUeK2d2O7O6M142SdsiE7z31scVuT5xF1PZU/cqpyzsvC9ud/b2HHadp2hGIzFvc9Ez+Tk3KpSXITl6oOGP1R9oI1zWdUw9QPQS20adupgPID5M2dE15b/sEJkpPKxhJVV+WTGOmFmlntjzKbt4z4xRJBd9936AN9U6XpDTzKr355ncMf01ukFxfrveakFZPkpkEqW79hkCmR20qLFWw7yVKFxE3eQo6w1nZgOPzETG0xEVw3NdBhzZ6RKU6NyNzhBwO8aXs9+UpzFPbrpwLXdyGP5JovgEb/dYa5mJh6zgr3h+t9bpVaa+pXbI0hIsfE5acc="
language: python

python:
- '3.6'

install:
- pip install flake8
- pip install coveralls

script:
- flake8 .
- python setup.py test

after_success:
- coveralls

before_deploy:
- python setup.py bdist_wheel

deploy:
- provider: pypi
  user: adalekin
  password:
    secure: K/YgmFna8cJNnV5iFPJBaW7qzCrgNmmL97EYM6BCRY7FaAZXLXCR+HEXwYWyqtU8iKrqq3uTmIdwkK0QTDe7HJY3aUmS6D3JkXm1x/UewB7EMd4ZSqdNtBz8FhtRw5ga5TxOqPs2Htm9Rs+E4Mqdwa27+jC4h4aiDHbdIAkyf45R5zXlQEFOTuqlOVA6JSk+xO5K1zzlkOxZAm8QMvwAZ/+u8xiTHngkFq5QCfPMWKBdRBZvx73mIAJ70iyweKn8N1X3+lhbDPskS2ovJv74w200iypupedkCBdjdmPVCoe+dg4Cjl+MzoRiXniiCRk4XQsRv66UhigJoErszbo8WmZFaqI4yAha5YjmGBgauZNOyYMQq7JRPtLaYKcwpaMsDoc7nt8PXMBozUELYVMT06qZs1QBGC0M1m66x2uH7K2fG0Kczh3+t67ETdMmExdjHIn2jsKQiD3Lzm71Bkanu1CBd/O7++mQU/hjtSdN17A5HdSiAvlGoWbP9BQht63Naif7hezCteCZGByEreJBL1TXsfWE7n+zALqBbv7r29/Aef7JuTtFSmNdLDDnmUU9h1PSjhByMUZt9MBQjE76LUwGd79P2GQHps54rsLfheh810KyJLzdGGTadEG6Rqt843PV67igaIS/edGtwoqtzaQlMY9Iv33F0jUUOilGXI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6

after_deploy:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t "${IMAGE_NAME}:${IMAGE_VERSION}" .
- docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
